### ISSUE TITLE
POD is not clear on how to use with Mojolicious (not Mojolicious::Lite)

### ISSUE THREAD

**Issue by akarelas** [augensalat/mojolicious-plugin-accesslog#2]
Documentation says I should write:

``` perl
# Mojolicious
$self->plugin(AccessLog => {log => '/var/log/mojo/access.log'});
```

But when I include the uname_helper setting as such:

``` perl
sub startup {
    my $app = shift;
    $app->plugin(AccessLog => {
        log => '/dev/null',
        uname_helper => 'set_username',
    });
    $app->hook(around_action => sub {
        my ($next, $c, $action) = @_;
        $c->set_username('alex');
    });
}
```

...then I get this error:

```
Can't locate object method "set_username" via package "Web::Ctrl1"
```

...where Web::Ctrl1 is the name of my controller that contains the route handlers. Everything else works on my website, except this, which produces this error.

How do I fix it? The AccessLog's documentation is not clear on this.

**Comment by augensalat** [comment]
I did not try to reproduce the described error, because the code has changed to what you described here.
If the issue still exists then please respond here and I might re-open this issue.
